baseurl = "http://kylechadha.com/"
languageCode = "en-us"
title = "Kyle Chadha"
theme = "purehugo"
Paginate = 10

[params]
  disqusShortname = "kylechadha"
  twitterName = "kylechadha"
  githubName = "kylechadha"
  description = "From my brain to yours."
